[package]
name = "hopsworks-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
log = { version = "0.4" }
env_logger = { version = "0.10" }
serde_json = { version = "1.0" }
apache-avro = { version = "0.14", features = ["derive"] }
polars = { version = "0.25.1", features = ["lazy", "avro"] }
polars-io = { version = "0.25.1", features = ["avro"] }
color-eyre = { version = "0.6.2" }
rdkafka = { version = "0.29.0", features = ["tokio", "libz", "ssl"] }
