[package]
name = "hopsworks-python"
edition = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
hopsworks-offline-store = { workspace = true }
hopsworks-online-store = { workspace = true }
hopsworks-kafka ={ workspace = true }
hopsworks-api = { workspace = true }
lazy_static = { version = "1.4" }
pyo3 = {workspace = true}
pyo3-log = {workspace = true}

[lib]
crate-type = ["cdylib"]
name = "hopsworks_rs"