[package]
name = "hopsworks-sdk"
edition = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]

hopsworks-offline-store = { workspace = true }
hopsworks-online-store = { workspace = true }
hopsworks-kafka ={ workspace = true }
hopsworks-api = { workspace = true }
lazy_static = { version = "1.4" }
tokio = { version = "1.0", features = ["full"] }
pyo3 = {workspace = true}
pyo3-log = {workspace = true}
log = {workspace = true}
color-eyre = {workspace = true}

[lib]
crate-type = ["cdylib"]
name = "hopsworks_sdk"